/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.FocusListener;

/**
 *
 * @author Cleiton
 */
public class FrmVendas extends javax.swing.JDialog {

    /**
     * Creates new form FrmVendas
     */
    public FrmVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnFundo = new java.awt.Panel();
        pnTituloVenda = new java.awt.Panel();
        lbTitulo = new java.awt.Label();
        pnDadosVeda = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        tfCodigoBarras = new javax.swing.JTextField();
        lbCodigoBarras = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        tfTotal = new javax.swing.JTextField();
        lbOpcoes = new javax.swing.JLabel();
        lbMenuFiscal = new javax.swing.JLabel();
        lbMenuAdicionarItem = new javax.swing.JLabel();
        lbFinalizarVenda = new javax.swing.JLabel();
        lbFinalizarVendaCupomFiscal = new javax.swing.JLabel();
        lbValorPago = new javax.swing.JLabel();
        tfValorPago = new javax.swing.JTextField();
        lbDesconto = new javax.swing.JLabel();
        tfDesconto = new javax.swing.JTextField();
        lbTroco = new javax.swing.JLabel();
        tfTroco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Venda");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnFundo.setBackground(new java.awt.Color(83, 131, 181));

        pnTituloVenda.setBackground(new java.awt.Color(22, 28, 1));

        lbTitulo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("C A I X A  -  L I V R E");

        javax.swing.GroupLayout pnTituloVendaLayout = new javax.swing.GroupLayout(pnTituloVenda);
        pnTituloVenda.setLayout(pnTituloVendaLayout);
        pnTituloVendaLayout.setHorizontalGroup(
            pnTituloVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloVendaLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTituloVendaLayout.setVerticalGroup(
            pnTituloVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDadosVeda.setBackground(new java.awt.Color(204, 204, 204));

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ITEM", "CÓDIGO", "DESCRICÃO", "VALOR"
            }
        ));
        tblVenda.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblVenda);

        javax.swing.GroupLayout pnDadosVedaLayout = new javax.swing.GroupLayout(pnDadosVeda);
        pnDadosVeda.setLayout(pnDadosVedaLayout);
        pnDadosVedaLayout.setHorizontalGroup(
            pnDadosVedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosVedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnDadosVedaLayout.setVerticalGroup(
            pnDadosVedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosVedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        tfCodigoBarras.setBackground(new java.awt.Color(51, 51, 51));
        tfCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfCodigoBarras.setForeground(new java.awt.Color(255, 255, 255));

        lbCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCodigoBarras.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigoBarras.setText("Informe o Código de Barras :");

        panel1.setBackground(new java.awt.Color(51, 51, 51));

        tfTotal.setBackground(new java.awt.Color(102, 102, 102));
        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfTotal.setForeground(new java.awt.Color(255, 255, 255));
        tfTotal.setText("R$");

        lbOpcoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbOpcoes.setForeground(new java.awt.Color(255, 255, 255));
        lbOpcoes.setText("F1 - Opções");

        lbMenuFiscal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMenuFiscal.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuFiscal.setText("F2 - Menu - Fiscal");

        lbMenuAdicionarItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMenuAdicionarItem.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuAdicionarItem.setText("F3 - Adicionar - Itens");

        lbFinalizarVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbFinalizarVenda.setForeground(new java.awt.Color(255, 255, 255));
        lbFinalizarVenda.setText("F4 - Finalizar Venda");

        lbFinalizarVendaCupomFiscal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbFinalizarVendaCupomFiscal.setForeground(new java.awt.Color(255, 255, 255));
        lbFinalizarVendaCupomFiscal.setText("F5 - Finalizar Venda com Cupom Fiscal");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lbOpcoes)
                        .addGap(47, 47, 47)
                        .addComponent(lbMenuFiscal)
                        .addGap(45, 45, 45)
                        .addComponent(lbMenuAdicionarItem))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lbFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFinalizarVendaCupomFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOpcoes)
                            .addComponent(lbMenuFiscal)
                            .addComponent(lbMenuAdicionarItem))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFinalizarVenda)
                            .addComponent(lbFinalizarVendaCupomFiscal))))
                .addGap(23, 23, 23))
        );

        lbValorPago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbValorPago.setForeground(new java.awt.Color(255, 255, 255));
        lbValorPago.setText("Valor Pago : ");

        tfValorPago.setBackground(new java.awt.Color(51, 51, 51));
        tfValorPago.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfValorPago.setForeground(new java.awt.Color(255, 255, 255));
        tfValorPago.setText("R$");

        lbDesconto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDesconto.setForeground(new java.awt.Color(255, 255, 255));
        lbDesconto.setText("Desconto : ");

        tfDesconto.setBackground(new java.awt.Color(51, 51, 51));
        tfDesconto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfDesconto.setForeground(new java.awt.Color(255, 255, 255));
        tfDesconto.setText("R$");

        lbTroco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTroco.setForeground(new java.awt.Color(255, 255, 255));
        lbTroco.setText("Troco : ");

        tfTroco.setBackground(new java.awt.Color(51, 51, 51));
        tfTroco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfTroco.setForeground(new java.awt.Color(255, 255, 255));
        tfTroco.setText("R$");

        javax.swing.GroupLayout pnFundoLayout = new javax.swing.GroupLayout(pnFundo);
        pnFundo.setLayout(pnFundoLayout);
        pnFundoLayout.setHorizontalGroup(
            pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTituloVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnFundoLayout.createSequentialGroup()
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnFundoLayout.createSequentialGroup()
                                .addComponent(lbDesconto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnFundoLayout.createSequentialGroup()
                                .addComponent(lbValorPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnFundoLayout.createSequentialGroup()
                                .addComponent(lbTroco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lbCodigoBarras)))
                .addGap(22, 22, 22)
                .addComponent(pnDadosVeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnFundoLayout.setVerticalGroup(
            pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundoLayout.createSequentialGroup()
                .addComponent(pnTituloVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDadosVeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbCodigoBarras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValorPago)
                            .addComponent(tfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDesconto)
                            .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTroco)
                            .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(pnFundo, gridBagConstraints);

        setSize(new java.awt.Dimension(1047, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigoBarras;
    private javax.swing.JLabel lbDesconto;
    private javax.swing.JLabel lbFinalizarVenda;
    private javax.swing.JLabel lbFinalizarVendaCupomFiscal;
    private javax.swing.JLabel lbMenuAdicionarItem;
    private javax.swing.JLabel lbMenuFiscal;
    private javax.swing.JLabel lbOpcoes;
    private java.awt.Label lbTitulo;
    private javax.swing.JLabel lbTroco;
    private javax.swing.JLabel lbValorPago;
    private java.awt.Panel panel1;
    private java.awt.Panel pnDadosVeda;
    private java.awt.Panel pnFundo;
    private java.awt.Panel pnTituloVenda;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField tfCodigoBarras;
    private javax.swing.JTextField tfDesconto;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTroco;
    private javax.swing.JTextField tfValorPago;
    // End of variables declaration//GEN-END:variables
}
