/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;

/**
 *
 * @author Cleiton
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new java.awt.Panel();
        btCliente = new javax.swing.JButton();
        lbCadastro = new javax.swing.JLabel();
        btFornecedor = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btOrcamento = new javax.swing.JButton();
        lbOperacional = new javax.swing.JLabel();
        btVendas = new javax.swing.JButton();
        btContasPagar = new javax.swing.JButton();
        btPedido = new javax.swing.JButton();
        btAbrirCaixa = new javax.swing.JButton();
        btFechamento = new javax.swing.JButton();
        lbRelatorios = new javax.swing.JLabel();
        btEstoques = new javax.swing.JButton();
        btCategoria = new javax.swing.JButton();
        btFicha = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        jMenuCaixa = new javax.swing.JMenu();
        jMenuEstoque = new javax.swing.JMenu();
        jMenuForecedor = new javax.swing.JMenu();
        jMenuVendas = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Software Padaria - Tela Principal");
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(255, 0, 0));

        pnPrincipal.setBackground(new java.awt.Color(21, 122, 247));

        btCliente.setBackground(new java.awt.Color(204, 255, 255));
        btCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/People_03.png"))); // NOI18N
        btCliente.setText("Cliente");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        lbCadastro.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 20)); // NOI18N
        lbCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lbCadastro.setText("Cadastros");

        btFornecedor.setBackground(new java.awt.Color(204, 255, 255));
        btFornecedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/run-icon (Custom).png"))); // NOI18N
        btFornecedor.setText("Fornecedor");
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });

        btProdutos.setBackground(new java.awt.Color(204, 255, 255));
        btProdutos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/produto_01.png"))); // NOI18N
        btProdutos.setText("Produto");
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });

        btOrcamento.setBackground(new java.awt.Color(204, 255, 255));
        btOrcamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/shopping-cart-up-icon (Custom).png"))); // NOI18N
        btOrcamento.setText("Orçamento");

        lbOperacional.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 20)); // NOI18N
        lbOperacional.setForeground(new java.awt.Color(255, 255, 255));
        lbOperacional.setText("Operacional");

        btVendas.setBackground(new java.awt.Color(204, 255, 255));
        btVendas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/venda_02.png"))); // NOI18N
        btVendas.setText("Vendas");
        btVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendasActionPerformed(evt);
            }
        });

        btContasPagar.setBackground(new java.awt.Color(204, 255, 255));
        btContasPagar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Financeiro_01.png"))); // NOI18N
        btContasPagar.setText("Contas Pagar");

        btPedido.setBackground(new java.awt.Color(204, 255, 255));
        btPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/orcamento_01.png"))); // NOI18N
        btPedido.setText("Pedido/Mesa");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });

        btAbrirCaixa.setBackground(new java.awt.Color(204, 255, 255));
        btAbrirCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/open-key-icon (Custom).png"))); // NOI18N
        btAbrirCaixa.setText("Abrir Caixa");

        btFechamento.setBackground(new java.awt.Color(204, 255, 255));
        btFechamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btFechamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Money_48 (Custom).png"))); // NOI18N
        btFechamento.setText("Fechamento");

        lbRelatorios.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 20)); // NOI18N
        lbRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        lbRelatorios.setText("Relatórios");

        btEstoques.setBackground(new java.awt.Color(204, 255, 255));
        btEstoques.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btEstoques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/estoque (Custom).png"))); // NOI18N
        btEstoques.setText("Estoque");

        btCategoria.setBackground(new java.awt.Color(204, 255, 255));
        btCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/conference-icon (Custom).png"))); // NOI18N
        btCategoria.setText("Categoria");
        btCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });

        btFicha.setBackground(new java.awt.Color(204, 255, 255));
        btFicha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/document-pencil-icon (Custom).png"))); // NOI18N
        btFicha.setText("Fichas");
        btFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOperacional, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(btCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btFechamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(btFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btEstoques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btContasPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(btFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbCadastro)
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lbOperacional)
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btContasPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEstoques, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lbRelatorios)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usuario_02.png"))); // NOI18N
        jMenuCliente.setText("Cliente");
        jMenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCliente);

        jMenuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/coins-icon (Custom).png"))); // NOI18N
        jMenuCaixa.setText("Caixa");
        jMenuCaixa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenuCaixa);

        jMenuEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/produto_05.png"))); // NOI18N
        jMenuEstoque.setText("Estoque");
        jMenuEstoque.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenuEstoque);

        jMenuForecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/talk-icon (Custom).png"))); // NOI18N
        jMenuForecedor.setText("Fornecedor");
        jMenuForecedor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuForecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuForecedorMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuForecedor);

        jMenuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/visa-icon (Custom).png"))); // NOI18N
        jMenuVendas.setText("Vendas");
        jMenuVendas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVendasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVendas);

        jMenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/servico_01.png"))); // NOI18N
        jMenuFerramentas.setText("Ferramentas");
        jMenuFerramentas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/webdev-cancel-icon (Custom).png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(803, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        FrmCliente frm = new FrmCliente(this, true);
        frm.setVisible(true);
        
    }//GEN-LAST:event_btClienteActionPerformed

    private void jMenuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClienteMouseClicked
        FrmCliente frm = new FrmCliente(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuClienteMouseClicked

    private void jMenuForecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuForecedorMouseClicked
        FrmFornecedor frm = new FrmFornecedor(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuForecedorMouseClicked

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        FrmFornecedor frm = new FrmFornecedor(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        FrmProduto frm = new FrmProduto(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaActionPerformed
        FrmCategoria frm = new FrmCategoria(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btCategoriaActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        JOptionPane.showMessageDialog(this, "O programa esta sendo encerrado !!!");
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVendasMouseClicked
        FrmVendas frm = new FrmVendas(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuVendasMouseClicked

    private void btVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendasActionPerformed
        FrmVendas frm = new FrmVendas(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btVendasActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        FrmPedido frm = new FrmPedido(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btPedidoActionPerformed

    private void btFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFichaActionPerformed
        FrmFichas frm = new FrmFichas(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirCaixa;
    private javax.swing.JButton btCategoria;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btContasPagar;
    private javax.swing.JButton btEstoques;
    private javax.swing.JButton btFechamento;
    private javax.swing.JButton btFicha;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btOrcamento;
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btVendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCaixa;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenu jMenuForecedor;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JLabel lbCadastro;
    private javax.swing.JLabel lbOperacional;
    private javax.swing.JLabel lbRelatorios;
    private java.awt.Panel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
